In [3]:
import numpy as np
from pickle import load

In [4]:
# Loading pretrained classifiers from pickle file
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir('/content/drive/MyDrive')

scaler = load(open('/content/drive/MyDrive/model/standard_scaler.pkl', 'rb'))
knn = load(open('./model/knn_model.pkl', 'rb'))
regressor = load(open('./model/lr_model.pkl', 'rb'))
rf = load(open('./model/rf_model.pkl', 'rb'))
xgb_reg = load(open('./model/xgb_model.pkl', 'rb'))


Mounted at /content/drive


In [5]:
# Read the Query Data

print("Enter ablong shell Details")
Sex = int(input('Enter the sex: '))
Length = float(input('Enter the SepalLengthWidth (in cm): '))
Diameter = float(input('Enter the Diameter (in cm): '))
Height = float(input('Enter the Height (in cm): '))
Whole_weight = float(input('Enter the Whole_weight (in cm): '))
Shucked_weight = float(input('Enter the Shucked_weight (in cm): '))
Viscera_weight = float(input('Enter the Viscera_weight (in cm): '))
Shell_weight =  float(input('Enter the Shell_weight (in cm): '))


Enter ablong shell Details
Enter the sex: 1
Enter the SepalLengthWidth (in cm): 0.660
Enter the Diameter (in cm): 0.530
Enter the Height (in cm): 0.170
Enter the Whole_weight (in cm): 1.3905	
Enter the Shucked_weight (in cm): 0.5905
Enter the Viscera_weight (in cm): 0.2120
Enter the Shell_weight (in cm): 0.4530


In [6]:
query_point = np.array([Sex, Length, Diameter, Height, Whole_weight,Shucked_weight,Viscera_weight, Shell_weight])

In [7]:
query_point

array([1.    , 0.66  , 0.53  , 0.17  , 1.3905, 0.5905, 0.212 , 0.453 ])

In [8]:
query_point.reshape(1, -1)


array([[1.    , 0.66  , 0.53  , 0.17  , 1.3905, 0.5905, 0.212 , 0.453 ]])

In [11]:
query_point = query_point.reshape(1, -1)
query_point_transformed = scaler.transform(query_point)


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [13]:
knn.predict(query_point_transformed)

array([14.16666667])

In [15]:
regressor.predict(query_point_transformed)

array([14.85981274])

In [16]:
rf.predict(query_point_transformed)

array([15.38])

In [17]:
xgb_reg.predict(query_point_transformed)

array([16.1272], dtype=float32)